apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    name: app-deploy
    app: demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app-pod
      app: demo-app
    
  template:
    metadata:
      name: app-pod
      labels:
        name: app-pod
        app: demo-app
    spec:
      containers:
        - name: app
          image: nginx
            
    
